--- #loop playbook example
- hosts: all
  user: root
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: install the packages tree telnet facter
    yum: name={{ item }} state=latest 
    with_items:
       - tree
       - facter
       - telnet
