--- #example of when condition

- hosts: all
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
  vars:
   redhat: httpd
   debian: apache2
  tasks:
  - name: installing hpptd on redhat distribution
    yum: name={{ redhat }} state=installed
    when: ansible_os_family=='RedHat'
    delegate_to: 127.0.0.1
  - name: installing apache2 on debian distribution
    yum: name={{ debian }} state=installed
    when: ansible_os_family=='Debian'
    delegate_to: 127.0.0.1
