--- #Example of Raw

- hosts: all
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
  tasks:
  - name: remove httpd services
    raw: yum -y remove httpd
  - name: stop Nginx service
    raw: systemctl stop nginx
  - name: Install tomcat
    raw: yum install -y tomcat

