<<<<<<< HEAD
--- # Full Include Tasks example

- hosts: all
  connection: ssh
  user: root
  gather_facts: yes
  become: yes
  tasks:
    - include: /root/list_packages.yml
    - include: /root/check_packages.yml 
=======
<<<<<<< HEAD
--- # Including list_packages.yml and check_packages.yml

- hosts: all
  user: root
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - include: /root/playbooks/list_packages.yml
  - include: /root/playbooks/check_packages.yml
=======
--- # Include Tasks Example

- hosts: local
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no 
  tasks:
    - include: /root/list_packages.yml
    - include: /root/check_packages.yml
>>>>>>> b2019c5225da3e4eb42dee94d0e24a47f105833f
>>>>>>> 0227605a5d8cdfa10118206f108658ba5914c574
