--- # practising of tasks

- hosts: all
  user: root
  connection: ssh
  gather_facts: yes
  become: yes
  vars:
   redhat: httpd
   debain: nginx
  tasks:
  - name: installing tree facter telnet and elinks using loop
    yum: name={{ item }} state=latest
    with_items:
    - tree
    - facter
    - telnet
    - elinks
  - name: installing redhat or apache based on os family
    yum: name=httpd state=latest
    when: ansible_os_family=='RedHat'
    notify: enablinghttpd
  - name: installing nginx
    yum: name=nginx state=latest
    when: ansible_os_family=='RedHat'
  - name: restart httpd  
    raw: systemctl restart httpd enabled=yes 
    when: ansible_os_family=='RedHat'
  - name: restart nginx
    raw: systemctl restart nginx enabled=yes
    when: ansible_os_family=='RedHat'
  handlers:
  - name: enablinghttpd
    service: name=httpd enabled=yes

    
