--- #EXAMPLE OF UNARCHIEVING WEBSERVER.YML.ZIP FILE

- hosts: localhost
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
  tasks:
  - name: Unarchieving webserver.yml.zip
    environment:
    unarchive: src=/root/roles/webserver.yml.zip dest=/root/playbooks
