<<<<<<< HEAD
--- # Example of until Module

=======
>>>>>>> b2019c5225da3e4eb42dee94d0e24a47f105833f
- hosts: localhost
  user: root
  connection: ssh
  become: yes
  gather_facts: yes
<<<<<<< HEAD
  tasks: 
  - name: Installing httpd
    action: yum name=httpd state=installed
  - name: RESTARTHTTPD
    service: name=httpd state=started
  - name: verify the httpd service status
    shell: systemctl status httpd
    register: result
    until: result.stdout.find("active (running)")
    ignore_errors: yes
=======
  tasks:
  - name: Checking service status of nginx
    raw: systemctl status nginx > /root/nginx.log
    register: result
    until: result.stdout.find("active (running)") != -1
    retries: 5
    delay: 15
>>>>>>> b2019c5225da3e4eb42dee94d0e24a47f105833f
  - debug: var=result
