--- # Control Playbook for webserver role

- hosts: localhost webserver
  connection: ssh
  user: root
  become: yes
  gather_facts: yes
  pre_tasks:
  - name: when the role start
    raw: date > /root/playbooks/startofrole.log
  - name: Remove httpd and telnet packages
    raw: yum -y remove httpd telnet
  - name: Removing logfile.txt on servers
    raw: rm -rf logfile.txt 
  - name: Remove dummy.sh
    raw: rm -rf dummy.sh
  roles:
  - webserver
  post_tasks:
  - name: when did the role finished
    raw: date > /root/playbooks/endofrole.log
  - name: Install telnet
    action: yum name=telnet state=latest 
